Feature/signed in home page fixes
COS301-SE-2024/Query-Builder pull request #434
Opened 2024-09-28 12:26 UTC by Keanumrc

- [x]  Changed and simplified the getOrgsLoggedIn endpoint to only return database envs the user has access to, and also role permissions
- [x] Changed the SignedInHomePage to only show database envs the user has access to, and to only show the button to add a database if the user has that specific permission
- [x] Changed tests to get them passing
  - removed tests for a helper function that was no longer needed

2024-09-28 19:07 UTC, ZaneAugustyn approved these changes

2024-09-28 19:08 UTC, ZaneAugustyn commented
Tests be failing

2024-09-28 19:09 UTC, ZaneAugustyn requested changes
Backend failing

2024-09-29 01:30 UTC, GremBleen approved these changes

2024-09-29 05:34 UTC, merged